## ch04 - section 4
-  연결 : 병합과 달리 두 테이블을 그대로 붙이는 작업
=> concat 함수
-  병합 : 두개의 테이블을 특정한 기준을 가지고 하나로 통합하는 작업
=> merge 함수

### 연결
- concat 함수
- titanic.csv 자료 활용

In [6]:
import pandas as pd

titanic = pd.read_csv('data/titanic.csv')
titanic

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [7]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerId  156 non-null    int64
 1   survived     156 non-null    int64
 2   pclass       156 non-null    int64
 3   name         156 non-null    str
 4   sex          156 non-null    str
 5   age          126 non-null    float64
 6   sibsp        156 non-null    int64
 7   parch        156 non-null    int64
 8   ticket       156 non-null    str
 9   fare         156 non-null    float64
 10  cabin        31 non-null     str
 11  embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [8]:
# 타이타닉 자료에서 일부만 추출하여 별도로 저장

test_a=titanic.iloc[:10,   :6]
test_b=titanic.iloc[10:15, :6]

print(len(test_a), len(test_b) )

10 5

In [9]:
# 위 두개자료 저장
test_a.to_csv('test_a.csv')
test_b.to_csv('test_b.csv')

In [10]:
# test_100 확인  // 100행 ,6개 컬럼
test_a.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerId  10 non-null     int64
 1   survived     10 non-null     int64
 2   pclass       10 non-null     int64
 3   name         10 non-null     str
 4   sex          10 non-null     str
 5   age          9 non-null      float64
dtypes: float64(1), int64(3), str(2)
memory usage: 612.0 bytes

In [11]:
# concat - 1
# 자료를 위아래로 합치기 -> 기본, 생략가능 axis=0
# 스키마가 같은 데이터프레임 합치기

total_df=pd.concat( [test_a, test_b] )

total_df

,passengerId,survived,pclass,name,sex,age
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0
5,6,0,3,"Moran, Mr. James",male,NaN
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0

In [13]:
# 스키마가 다른 데이터프레임 준비
# test_b 데이터프레임에서 왼쪽부터 4개의 컬럼만 추출하여 x 에 저장

x = test_b.iloc[:, :4]
x

    passengerId  survived  pclass                                  name
10           11         1       3       Sandstrom, Miss. Marguerite Rut
11           12         1       1              Bonnell, Miss. Elizabeth
12           13         0       3        Saundercock, Mr. William Henry
13           14         0       3           Andersson, Mr. Anders Johan
14           15         0       3  Vestrom, Miss. Hulda Amanda Adolfina

In [36]:
# concat - 2
# 스키마가 다른 데이터프레임 합치기

# 데이터준비
# test_a : 6개 컬럼 // test_b : 4개 컬럼
test_a=titanic.iloc[:10,   :6]
test_b=titanic.iloc[10:15, :4]

# 결합
total_df=pd.concat([test_a, test_b], axis=1)
total_df

# 없는 컬럼부분 -> NaN으로 채워짐

,passengerId,survived,pclass,name,sex,age,passengerId,survived,pclass,name
0,1.0,0.0,3.0,"Braund, Mr. Owen Harris",male,22.0,NaN,NaN,NaN,NaN
1,2.0,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,NaN,NaN,NaN,NaN
2,3.0,1.0,3.0,"Heikkinen, Miss. Laina",female,26.0,NaN,NaN,NaN,NaN
3,4.0,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,NaN,NaN,NaN,NaN
4,5.0,0.0,3.0,"Allen, Mr. William Henry",male,35.0,NaN,NaN,NaN,NaN
5,6.0,0.0,3.0,"Moran, Mr. James",male,NaN,NaN,NaN,NaN,NaN
6,7.0,0.0,1.0,"McCarthy, Mr. Timothy J",male,54.0,NaN,NaN,NaN,NaN
7,8.0,0.0,3.0,"Palsson, Master. Gosta Leonard",male,2.0,NaN,NaN,NaN,NaN
8,9.0,1.0,3.0,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,NaN,NaN,NaN,NaN
9,10.0,1.0,2.0,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,11.0,1.0,3.0,"Sandstrom, Miss. Marguerite Rut"
11,NaN,NaN,NaN,NaN,NaN,NaN,12.0,1.0,1.0,"Bonnell, Miss. Elizabeth"
12,NaN,NaN,NaN,NaN,NaN,NaN,13.0,0.0,3.0,"Saundercock, Mr. William Henry"
13,NaN,NaN,NaN,NaN,NaN,NaN,14.0,0.0,3.0,"Andersson, Mr. Anders Johan"
14,NaN,NaN,NaN,NaN,NaN,NaN,15.0,0.0,3.0,"Vestrom, Miss. Hulda Amanda Adolfina"

In [15]:
# concat - 3
# 좌우로 붙이기 : 옆으로 ==> axis=1

# 데이터준비
# test_a : 6개 컬럼 // test_b : 4개 컬럼
test_a=titanic.iloc[:10,   :6]
test_b=titanic.iloc[10:15, :4]

# 결합
total_df=pd.concat([test_a, test_b], axis=1)
total_df

# concat 결과 -> ???

,passengerId,survived,pclass,name,sex,age,passengerId,survived,pclass,name
0,1.0,0.0,3.0,"Braund, Mr. Owen Harris",male,22.0,NaN,NaN,NaN,NaN
1,2.0,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,NaN,NaN,NaN,NaN
2,3.0,1.0,3.0,"Heikkinen, Miss. Laina",female,26.0,NaN,NaN,NaN,NaN
3,4.0,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,NaN,NaN,NaN,NaN
4,5.0,0.0,3.0,"Allen, Mr. William Henry",male,35.0,NaN,NaN,NaN,NaN
5,6.0,0.0,3.0,"Moran, Mr. James",male,NaN,NaN,NaN,NaN,NaN
6,7.0,0.0,1.0,"McCarthy, Mr. Timothy J",male,54.0,NaN,NaN,NaN,NaN
7,8.0,0.0,3.0,"Palsson, Master. Gosta Leonard",male,2.0,NaN,NaN,NaN,NaN
8,9.0,1.0,3.0,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,NaN,NaN,NaN,NaN
9,10.0,1.0,2.0,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,11.0,1.0,3.0,"Sandstrom, Miss. Marguerite Rut"
11,NaN,NaN,NaN,NaN,NaN,NaN,12.0,1.0,1.0,"Bonnell, Miss. Elizabeth"
12,NaN,NaN,NaN,NaN,NaN,NaN,13.0,0.0,3.0,"Saundercock, Mr. William Henry"
13,NaN,NaN,NaN,NaN,NaN,NaN,14.0,0.0,3.0,"Andersson, Mr. Anders Johan"
14,NaN,NaN,NaN,NaN,NaN,NaN,15.0,0.0,3.0,"Vestrom, Miss. Hulda Amanda Adolfina"

## 병합
- merge 함수
- titanic.csv 자료 활용

In [16]:
import pandas as pd

titanic = pd.read_csv('data/titanic.csv')  # 코랩에 titanic.csv 업로드 한 후에 코드 실행
titanic

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

### merge - 1
- 일반적 병합

In [17]:
# 준비 작업 - df1
# 실습의 편의를 위해 4개 컬럼 / 10개 행만 추출  ==> df1 저장

df1=titanic.loc[:9, ['name', 'pclass', 'sex', 'age']]
df1

                                                name  pclass     sex   age
0                            Braund, Mr. Owen Harris       3    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1  female  38.0
2                             Heikkinen, Miss. Laina       3  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1  female  35.0
4                           Allen, Mr. William Henry       3    male  35.0
5                                   Moran, Mr. James       3    male   NaN
6                            McCarthy, Mr. Timothy J       1    male  54.0
7                     Palsson, Master. Gosta Leonard       3    male   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)       3  female  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)       2  female  14.0

In [ ]:
# name 컬럼의 값을 정제

# name 컬럼의 값을 ',' 이전의 값만을 추출해 보자
# 해당 컬럼의 값을 문자열로 바꾸고, ','를 기준으로 구분하여 문자열을 분리
# 분리된 문자열은 리스트에 저장 [ ?, ?, ....]

# 해당 컬럼의 값을 문자열로 바꾸고, ','를 기준으로 구분하여 문자열을 분리한다.
df1['name'].str.split(',') # => ['Braund', ' Mr. Owen Harris']

0                           [Braund,  Mr. Owen Harris]
1    [Cumings,  Mrs. John Bradley (Florence Briggs ...
2                            [Heikkinen,  Miss. Laina]
3      [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                          [Allen,  Mr. William Henry]
5                                  [Moran,  Mr. James]
6                           [McCarthy,  Mr. Timothy J]
7                    [Palsson,  Master. Gosta Leonard]
8    [Johnson,  Mrs. Oscar W (Elisabeth Vilhelmina ...
9               [Nasser,  Mrs. Nicholas (Adele Achem)]
Name: name, dtype: object

In [19]:
# , 구분하고 첫번째 문자열
df1['name'].str.split(',').str[0]

0       Braund
1      Cumings
2    Heikkinen
3     Futrelle
4        Allen
5        Moran
6     McCarthy
7      Palsson
8      Johnson
9       Nasser
Name: name, dtype: object

In [20]:
# 준비 작업 - df1
# 실습의 편의를 위해 4개 컬럼 / 10개 행만 추출  ==> df1 저장

df1=titanic.loc[:9, ['name', 'pclass', 'sex', 'age']]
df1['name'] = df1['name'].str.split(',').str[0]
df1

        name  pclass     sex   age
0     Braund       3    male  22.0
1    Cumings       1  female  38.0
2  Heikkinen       3  female  26.0
3   Futrelle       1  female  35.0
4      Allen       3    male  35.0
5      Moran       3    male   NaN
6   McCarthy       1    male  54.0
7    Palsson       3    male   2.0
8    Johnson       3  female  27.0
9     Nasser       2  female  14.0

In [21]:
# 준비 작업 - df2
# 실습의 편의를 위해 2개 컬럼 / 10개 행만 추출  ==> df2 저장

df2=titanic.loc[:9, ['name', 'survived']]
df2['name'] = df2['name'].str.split(',').str[0]
df2

        name  survived
0     Braund         0
1    Cumings         1
2  Heikkinen         1
3   Futrelle         1
4      Allen         0
5      Moran         0
6   McCarthy         0
7    Palsson         0
8    Johnson         1
9     Nasser         1

In [22]:
# 두 데이터프레임의 같은 컬럼의 값으로 머지 => name 으로 머지

merge_inner=pd.merge(df1, df2)
merge_inner

        name  pclass     sex   age  survived
0     Braund       3    male  22.0         0
1    Cumings       1  female  38.0         1
2  Heikkinen       3  female  26.0         1
3   Futrelle       1  female  35.0         1
4      Allen       3    male  35.0         0
5      Moran       3    male   NaN         0
6   McCarthy       1    male  54.0         0
7    Palsson       3    male   2.0         0
8    Johnson       3  female  27.0         1
9     Nasser       2  female  14.0         1

### merge - 2
- name  같은 사람이 있는 경우

In [23]:
# 데이터 준비 - df3

df3=titanic.loc[:9, ['name', 'pclass', 'sex', 'age']]
df3['name'] = df3['name'].str.split(',').str[0]

# 상위 두개의 name을 'Jone'으로 변경
df3.loc [:1, 'name'] = 'Jone'
df3

        name  pclass     sex   age
0       Jone       3    male  22.0
1       Jone       1  female  38.0
2  Heikkinen       3  female  26.0
3   Futrelle       1  female  35.0
4      Allen       3    male  35.0
5      Moran       3    male   NaN
6   McCarthy       1    male  54.0
7    Palsson       3    male   2.0
8    Johnson       3  female  27.0
9     Nasser       2  female  14.0

In [38]:
# 데이터 준비 - df4

df4=titanic.loc[:9, ['name', 'survived']]
df4['name'] = df4['name'].str.split(',').str[0]

df4.loc[0:1, 'name']='John'
df4

        name  survived
0       John         0
1       John         1
2  Heikkinen         1
3   Futrelle         1
4      Allen         0
5      Moran         0
6   McCarthy         0
7    Palsson         0
8    Johnson         1
9     Nasser         1

In [39]:
# 두 데이터프레임의 같은 컬럼의 값으로 머지 => name 으로 머지

merge_inner=pd.merge(df3, df4)
merge_inner

        name  pclass     sex   age  survived
0  Heikkinen       3  female  26.0         1
1   Futrelle       1  female  35.0         1
2      Allen       3    male  35.0         0
3      Moran       3    male   NaN         0
4   McCarthy       1    male  54.0         0
5    Palsson       3    male   2.0         0
6    Johnson       3  female  27.0         1
7     Nasser       2  female  14.0         1

### merge - 3
- name이 공백이 있는 데이터

In [40]:
# 데이터준비 - df5

df5=titanic.loc[:9, ['name', 'pclass', 'sex', 'age']]
df5['name'] = df5['name'].str.split(',').str[0]
df5

        name  pclass     sex   age
0     Braund       3    male  22.0
1    Cumings       1  female  38.0
2  Heikkinen       3  female  26.0
3   Futrelle       1  female  35.0
4      Allen       3    male  35.0
5      Moran       3    male   NaN
6   McCarthy       1    male  54.0
7    Palsson       3    male   2.0
8    Johnson       3  female  27.0
9     Nasser       2  female  14.0

In [41]:
# 데이터준비 - df6

df6=titanic.loc[:9, ['name', 'survived']]
df6['name'] = df6['name'].str.split(',').str[0]

# 하위 두개의 name 컬럼의 이름을 지운다
df6.loc[8:9, 'name'] = ''
df6

        name  survived
0     Braund         0
1    Cumings         1
2  Heikkinen         1
3   Futrelle         1
4      Allen         0
5      Moran         0
6   McCarthy         0
7    Palsson         0
8                    1
9                    1

In [42]:
# name이 공백의 임의의 데이터 병합

merge_inner=pd.merge(df5, df6)
merge_inner

# 머지결과 : name이 공백인 행은 병합되지 않음

        name  pclass     sex   age  survived
0     Braund       3    male  22.0         0
1    Cumings       1  female  38.0         1
2  Heikkinen       3  female  26.0         1
3   Futrelle       1  female  35.0         1
4      Allen       3    male  35.0         0
5      Moran       3    male   NaN         0
6   McCarthy       1    male  54.0         0
7    Palsson       3    male   2.0         0

### merge - 4
- how, on 사용법

In [30]:
#  how='inner' :
#  일반 조인 : 매칭되는 것만 포함

merge_inner=pd.merge(df5, df6, how='inner', on='name')   # how='inner' 기본값
merge_inner

        name  pclass     sex   age  survived
0     Braund       3    male  22.0         0
1    Cumings       1  female  38.0         1
2  Heikkinen       3  female  26.0         1
3   Futrelle       1  female  35.0         1
4      Allen       3    male  35.0         0
5      Moran       3    male   NaN         0
6   McCarthy       1    male  54.0         0
7    Palsson       3    male   2.0         0

In [31]:
#  머지에 참여하지 않은 값도 포함
#  outer 조인  : how='outer'  ==> full outer 효과

merge = pd.merge(df5, df6, how='outer', on='name')
merge

         name  pclass     sex   age  survived
0                 NaN     NaN   NaN       1.0
1                 NaN     NaN   NaN       1.0
2       Allen     3.0    male  35.0       0.0
3      Braund     3.0    male  22.0       0.0
4     Cumings     1.0  female  38.0       1.0
5    Futrelle     1.0  female  35.0       1.0
6   Heikkinen     3.0  female  26.0       1.0
7     Johnson     3.0  female  27.0       NaN
8    McCarthy     1.0    male  54.0       0.0
9       Moran     3.0    male   NaN       0.0
10     Nasser     2.0  female  14.0       NaN
11    Palsson     3.0    male   2.0       0.0

In [32]:
#  머지에 참여하지 않은 값도 포함
#  outer 조인  : how='left'

merge = pd.merge(df5,df6, how='left', on='name')
#merge = pd.merge(df5,df6, how='right', on='name')
merge

        name  pclass     sex   age  survived
0     Braund       3    male  22.0       0.0
1    Cumings       1  female  38.0       1.0
2  Heikkinen       3  female  26.0       1.0
3   Futrelle       1  female  35.0       1.0
4      Allen       3    male  35.0       0.0
5      Moran       3    male   NaN       0.0
6   McCarthy       1    male  54.0       0.0
7    Palsson       3    male   2.0       0.0
8    Johnson       3  female  27.0       NaN
9     Nasser       2  female  14.0       NaN

In [35]:
# 두 자료의 컬럼이 다를 경우 -> 흔히 있다. 이름 , 성명
# 머지할 컬럼의 이름을 지정

# df6 name -> name1 컬럼명 변경
df6.columns = ['name1', 'survived']

merge_left=pd.merge(df5, df6, how='inner', left_on='name', right_on='name1')
merge

# 머지 결과 : name 컬럼과 name1 컬럼이 모두 존재

        name  pclass     sex   age  survived
0     Braund       3    male  22.0       0.0
1    Cumings       1  female  38.0       1.0
2  Heikkinen       3  female  26.0       1.0
3   Futrelle       1  female  35.0       1.0
4      Allen       3    male  35.0       0.0
5      Moran       3    male   NaN       0.0
6   McCarthy       1    male  54.0       0.0
7    Palsson       3    male   2.0       0.0
8    Johnson       3  female  27.0       NaN
9     Nasser       2  female  14.0       NaN

In [44]:
merge=pd.merge(df5, df6, how='inner', on='name')
merge

        name  pclass     sex   age  survived
0     Braund       3    male  22.0         0
1    Cumings       1  female  38.0         1
2  Heikkinen       3  female  26.0         1
3   Futrelle       1  female  35.0         1
4      Allen       3    male  35.0         0
5      Moran       3    male   NaN         0
6   McCarthy       1    male  54.0         0
7    Palsson       3    male   2.0         0

In [46]:
merge=pd.merge(df5, df6, how='outer', on='name')
merge

         name  pclass     sex   age  survived
0                 NaN     NaN   NaN       1.0
1                 NaN     NaN   NaN       1.0
2       Allen     3.0    male  35.0       0.0
3      Braund     3.0    male  22.0       0.0
4     Cumings     1.0  female  38.0       1.0
5    Futrelle     1.0  female  35.0       1.0
6   Heikkinen     3.0  female  26.0       1.0
7     Johnson     3.0  female  27.0       NaN
8    McCarthy     1.0    male  54.0       0.0
9       Moran     3.0    male   NaN       0.0
10     Nasser     2.0  female  14.0       NaN
11    Palsson     3.0    male   2.0       0.0

In [ ]:
merge=pd.merge(df5, df6, how='left', on='name')
# merge=pd.merge(df5, df6, how='right', on='name')
merge

        name  pclass     sex   age  survived
0     Braund       3    male  22.0       0.0
1    Cumings       1  female  38.0       1.0
2  Heikkinen       3  female  26.0       1.0
3   Futrelle       1  female  35.0       1.0
4      Allen       3    male  35.0       0.0
5      Moran       3    male   NaN       0.0
6   McCarthy       1    male  54.0       0.0
7    Palsson       3    male   2.0       0.0
8    Johnson       3  female  27.0       NaN
9     Nasser       2  female  14.0       NaN