### 판다스
- 2차원 테이블을 다루는 도구
- 시리즈 : 인덱스 + 값
- 데이터프레임 : 인덱스 + 열 + 값 ==> 시리즈+시리즈+... 테이블 형태
-----
- 판다스 생성
- 데이터 추출
- 그룹별 집계
- 병합과 연결

### 시리즈 생성

In [22]:
import numpy as np  # numpy 모듈 호출
import pandas as pd  # pandas 모듈 호출
from pandas import Series, DataFrame

In [9]:
# 리스트로 시리즈 생성

list_data = [1,2,3,4,5]
list_name = ["a","b","c","d","e"]
example_obj = pd.Series(data = list_data, index=list_name)
example_obj

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [17]:
example_obj.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [18]:
example_obj.values

array([1, 2, 3, 4, 5])

In [19]:
# 시리즈는 1차원 배열
type(example_obj.values)

numpy.ndarray

In [20]:
# 행,열 인덱스의 이름 설정하기
example_obj.name = "number"
example_obj.index.name = "id"
example_obj

id
a    1
b    2
c    3
d    4
e    5
Name: number, dtype: int64

In [23]:
# 딕셔너리로 시리즈 생성

dict_data = {"a":1, "b":2, "c":3, "d":4, "e":5 }
example_obj = Series(dict_data)
example_obj

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [24]:
# 데이터와 인덱스의 길이가 다르면
# 데이터 : 5, 인덱스 : 8 ==> ???

dict_data_1 = {"a":1, "b":2, "c":3, "d":4, "e":5}
indexes = ["a","b","c","d","e","f","g","h"]
series_obj_1 = Series(dict_data_1, index=indexes)
series_obj_1

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    NaN
g    NaN
h    NaN
dtype: float64

### 데이터프레임 생성
- 리스트로 생성
- 딕셔너리로 생성
- url로 생성

In [25]:
# 1차원 리스트 -> 데이터프레임으로 생성

aa = [1, 2, 3, 4, 5]
df1  = pd.DataFrame(aa)
df1

   0
0  1
1  2
2  3
3  4
4  5

In [31]:
# 2차원 리스트 -> 데이터프레임으로 생성

aa =  [ ['정약용', 70, 80, 100],
        ['이순신', 100, 80, 70],
        ['이율곡', 90, 95, 90]  ]
print(aa)
print('-'*80)

df2 = pd.DataFrame(aa)
df2

[['정약용', 70, 80, 100], ['이순신', 100, 80, 70], ['이율곡', 90, 95, 90]]
--------------------------------------------------------------------------------

     0    1   2    3
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [ ]:
# url -> 데이터프레임 생성

data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
df_data = pd.read_csv(data_url, sep='\s+', header = None)

# sep='\s+' --> 공백으로 구분된 데이터

df3 = pd.DataFrame(df_data)
df3

In [ ]:
# 딕셔너리 -> 데이터프레임 생성
# 키 -> 열 이름 , 값 -> 값

dic = {   'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
          'last_name' : ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze'],
          'age'       : [42, 52, 36, 24, 73],
          'city'      : ['San Francisco', 'Baltimore', 'Miami', 'Douglas', 'Boston']}

df = pd.DataFrame(dic)

df

  first_name last_name  age           city
0      Jason    Miller   42  San Francisco
1      Molly  Jacobson   52      Baltimore
2       Tina       Ali   36          Miami
3       Jake    Milner   24        Douglas
4        Amy     Cooze   73         Boston

In [35]:
# 데이터 중에 일부 컬럼만 데이터프레임으로 생성

df1 = pd.DataFrame(dic, columns = ["age", "city"])

In [36]:
# 데이터가 존재하지 않는 열을 추가하면 해당 열에는 NaN 값들 추가

df2 = DataFrame(dic,
                columns = ["first_name","last_name","age", "city", "debut"]
                )
df2

  first_name last_name  age           city debut
0      Jason    Miller   42  San Francisco   NaN
1      Molly  Jacobson   52      Baltimore   NaN
2       Tina       Ali   36          Miami   NaN
3       Jake    Milner   24        Douglas   NaN
4        Amy     Cooze   73         Boston   NaN

### 파일입출력
- 예제파일 : data 폴더 자료
- 파일 코랩에 업로드 : 직접업로드, 간접업로드

In [47]:
df1 = pd.read_csv("data/파일입출력_실습데이터/df_sample.csv")
df1

   name  java  basic  python
0   kim    70     75      80
1   lee    80     85      90
2  park    90     98     100

In [ ]:
# Excel 파일 -> 데이터프레임으로 생성

df2 = pd.read_excel("data/파일입출력_실습데이터/nation.xlsx", index_col="국적코드")
df2

      성별    입국객수    증가수
국적코드
A01   남성  125000   8000
A01   여성  130000  10000
A05   남성     300     10
A05   여성     200     50
A06   남성  158912  24486
A06   여성  325000  63466

In [ ]:
# json 파일 -> 데이터프레임으로 생성

df2 = pd.read_json("data/파일입출력_실습데이터/df_sample.json")
df2

           name  year        developer opensource
pandas           2008    Wes Mckinneye       True
NumPy            2006  Travis Oliphant       True
matplotlib       2003   John D. Hunter       True

In [ ]:
# 데이터프레임 -> csv, excel, json 파일로 저장하기

df.to_csv("aaa.csv")
df.to_excel("bbb.xlsx")
df.to_json("ccc.json")

### 데이터 추출
- 일반 방법
- loc 함수
- iloc 함수

In [2]:
import pandas as pd # pandas 모듈 호출
import numpy as np # numpy 모듈 호출

In [10]:
# 엑셀 파일 ( excel-comp-data.xlsx ) 읽어서 데이터프레임에 저장

df = pd.read_excel("data/4장 교재 데이터/excel-comp-data.xlsx")
df

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
1,320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
4,121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000
5,132971,"Williamson, Schumm and Hettinger",89403 Casimer Spring,Jeremieburgh,Arkansas,62785,150000,120000,35000
6,145068,Casper LLC,340 Consuela Bridge Apt. 400,Lake Gabriellaton,Mississipi,18008,62000,120000,70000
7,205217,Kovacek-Johnston,91971 Cronin Vista Suite 601,Deronville,RhodeIsland,53461,145000,95000,35000
8,209744,Champlin-Morar,26739 Grant Lock,Lake Juliannton,Pennsylvania,64415,70000,95000,35000
9,212303,Gerhold-Maggio,366 Maggio Grove Apt. 998,North Ras,Idaho,46308,70000,120000,35000
10,214098,"Goodwin, Homenick and Jerde",649 Cierra Forks Apt. 078,Rosaberg,Tenessee,47743,45000,120000,55000
11,231907,Hahn-Moore,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
12,242368,"Frami, Anderson and Donnelly",182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
13,268755,Walsh-Haley,2624 Beatty Parkways,Goodwinmouth,RhodeIsland,31919,55000,120000,35000
14,273274,McDermott PLC,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000

In [11]:
# 위에서 5개 행만 검색

df.head(5)

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
1,320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
4,121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000

In [12]:
# 끝에서 5개 행만 검색

df.tail(5)

,account,name,street,city,state,postal-code,Jan,Feb,Mar
10,214098,"Goodwin, Homenick and Jerde",649 Cierra Forks Apt. 078,Rosaberg,Tenessee,47743,45000,120000,55000
11,231907,Hahn-Moore,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
12,242368,"Frami, Anderson and Donnelly",182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
13,268755,Walsh-Haley,2624 Beatty Parkways,Goodwinmouth,RhodeIsland,31919,55000,120000,35000
14,273274,McDermott PLC,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000

In [13]:
# 행 / 열 바꾸기

df.head(3).T

,0,1,2
account,211829,320563,648336
name,"Kerluke, Koepp and Hilpert",Walter-Trantow,"Bashirian, Kunde and Price"
street,34456 Sean Highway,1311 Alvis Tunnel,62184 Schamberger Underpass Apt. 231
city,New Jaycob,Port Khadijah,New Lilianland
state,Texas,NorthCarolina,Iowa
postal-code,28752,38365,76517
Jan,10000,95000,91000
Feb,62000,45000,120000
Mar,35000,35000,35000

In [14]:
# 원하는 열 하나 검색

df["name"]         # 시리즈로 추출

0           Kerluke, Koepp and Hilpert
1                       Walter-Trantow
2           Bashirian, Kunde and Price
3          D'Amore, Gleichner and Bode
4                        Bauch-Goldner
5     Williamson, Schumm and Hettinger
6                           Casper LLC
7                     Kovacek-Johnston
8                       Champlin-Morar
9                       Gerhold-Maggio
10         Goodwin, Homenick and Jerde
11                          Hahn-Moore
12        Frami, Anderson and Donnelly
13                         Walsh-Haley
14                       McDermott PLC
Name: name, dtype: str

In [16]:
# 원하는 열 여러개 검색

df[['name', 'postal-code']]

                                name  postal-code
0         Kerluke, Koepp and Hilpert        28752
1                     Walter-Trantow        38365
2         Bashirian, Kunde and Price        76517
3        D'Amore, Gleichner and Bode        46021
4                      Bauch-Goldner        49681
5   Williamson, Schumm and Hettinger        62785
6                         Casper LLC        18008
7                   Kovacek-Johnston        53461
8                     Champlin-Morar        64415
9                     Gerhold-Maggio        46308
10       Goodwin, Homenick and Jerde        47743
11                        Hahn-Moore        31415
12      Frami, Anderson and Donnelly        72686
13                       Walsh-Haley        31919
14                     McDermott PLC        27933

In [ ]:
# 슬라이싱-1

### 슬라이싱 함수 : loc
- df.loc[] : "레이블 기반 인덱싱"을 지원
- 행이름, 열이름으로 데이터를 검색
- df.loc[행_레이블, 열_레이블]
- df.loc[행범위, 열범위]

In [38]:
# 실습을 위해 titanic.csv 를 업로드

import pandas as pd # pandas 모듈 호출
import numpy as np # numpy 모듈 호출

df = pd.read_csv("data/파일입출력_실습데이터/titanic.csv")
df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [39]:
# 데이터프레임 전체적인 정보 확인 -> info()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerId  156 non-null    int64
 1   survived     156 non-null    int64
 2   pclass       156 non-null    int64
 3   name         156 non-null    str
 4   sex          156 non-null    str
 5   age          126 non-null    float64
 6   sibsp        156 non-null    int64
 7   parch        156 non-null    int64
 8   ticket       156 non-null    str
 9   fare         156 non-null    float64
 10  cabin        31 non-null     str
 11  embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [40]:
# 원하는 행만
df.loc[[1,3,6]]

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [41]:
# 원하는 행의 범위
# 열이름 생략가능 / 생략시 모든 열
df.loc[2:5]

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [ ]:
# 원하는 열 하나

In [ ]:
# 원하는 열들만 : 'name', 'age' 두게 열만 검색

In [ ]:
# 행이름, 열이름

### 슬라이싱 함수 : iloc
- integer-location : 위치기반
- loc 함수는 이름으로 접근 / iloc 함수는 위치(숫자)로 접근
- 사용법은 loc와 같다

In [43]:
import pandas as pd
import numpy as np

df = pd.read_csv("titanic.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'titanic.csv'

In [ ]:
# 행검색
df.iloc[0:5]     # 인덱스이므로 0 부터 5 이전까지

In [ ]:
# 특정 행열 검색

In [ ]:
# 특정범위 행열검색

### 행열 삭제
- drop 함수
- df.drop(행또는열이름, axis=1)

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("titanic.csv")   # titanic.csv 파일이 코랩에 업로드 되어 있어야 한다
df.head()

In [ ]:
# 데이터프레임 복사

df_a = df
print(id(df), id(df_a))

df_copy = df.loc[:]
print(id(df), id(df_copy))

In [ ]:
df_copy

In [ ]:
# df_copy 데이터프레임에서 passengerId 열을 삭제

df_copy.drop( 'passengerId', axis=1)  # passengerId 열 삭제

In [ ]:
# df_copy 데이터프레임에서 여러 열을 삭제

df_copy.drop( ['passengerId','pclass'], axis=1)  # passengerId 열 삭제

# 실제로 삭제되지는 않고 삭제되어서 보여야 진다.

In [ ]:
df_copy

In [ ]:
# 삭제 결과를 저장하려면 - 1

x=df_copy.drop( ['passengerId','pclass'], axis=1)
x

In [ ]:
# 삭제 결과를 저장하려면 - 2
# 한번만 실행할 것 / 다시하면 해당 컬럼이 없어서 오류가 난다

df_copy.drop('survived', axis=1, inplace=True)
df_copy

### 조건검색
- 행범위 위치에 조건을 준다.
- lic , iloc 동일

In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv("titanic.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'titanic.csv'

In [ ]:
# 나이가 5세 미만 자료만

df.loc[ ??? ]

In [ ]:
# 나이가 5세 미만 자료의 이름과 나이

???

In [ ]:
# 조건이 여러개 : &, |, ~
# 나이가 10미만 중에 생존한 탑승객의 이름과 나이

df.loc[  ???  , ['name','age'] ]

In [ ]:
# 10세 미만이 아닌 탑승객의 이름과 나이
df.loc[ ??? ]

### 셀프스터디
- 조건 검색에 대한 코드를 완성해 주세요

In [ ]:
# 셀프스터디 실습을 위한 데이터프레임 생성

import pandas as pd

df1 = pd.DataFrame({'name' : ['Minsoo','Minju','Yeomin','Hyeri','Junghun','Sunny','Bummee','Luna'],
                   'old'  : [33,25,19,25,32,36,23,36],
                   'sex'  : ['M','W','W','W','M','W','M','W'],
                   'score1': [91,50,69,98,72,85,43,61],
                   'score2': [65,77,56,82,79,91,71,63],
                   'time' : [30,95,64,88,34,69,15,25],
                   })
df1

In [ ]:
# 나이가 30대 이상인 자료만 검색

In [ ]:
# score1이나 score2 둘 중 하나가 80점 이상인 자료만 검색

In [ ]:
# 나이가 20대이거나 문제를 푸는데 걸리는 시간이 40초보다 짧은 자료만 검색

In [ ]:
# 깔끔하게 조건을 저장하고 사용하면 편하다.

con1 = (df['sex']=='W')
con2 = (df['score1']<70)

# df[ con1 & con2 ]
# df[ con1 | con2 ]
# df[ ~con1]

df[ ~( con1 & con2 ) ]