## 데이터전처리 개념
- 통계, 머신러닝 훈련 전 데이터를 정제하는 전과정

### 결측치 처리 : 삭제
- 데이터가 없는 행이나 열을 삭제
- dropna()
- dropna(how=?)
- dropna(thresh=?)

In [10]:
import pandas as pd
import numpy as np

raw_data = {'first_name': ['Jason', np.nan, 'Tina', 'Jake', 'Amy'],
            'last_name': ['Miller', np.nan, 'Ali', 'Milner', 'Cooze'],
            'age': [42, np.nan, 36, 24, 73],
            'sex': ['m', np.nan, 'f', 'm', 'f'],
            'preTestScore': [4, np.nan, np.nan, 2, 3],
            'postTestScore': [25, np.nan, np.nan, 62, 70] }

# df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'sex', 'preTestScore', 'postTestScore'])
df = pd.DataFrame(raw_data)
df

  first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0           25.0
1        NaN       NaN   NaN  NaN           NaN            NaN
2       Tina       Ali  36.0    f           NaN            NaN
3       Jake    Milner  24.0    m           2.0           62.0
4        Amy     Cooze  73.0    f           3.0           70.0

In [ ]:
# 하나씩 실행해 보자
# df.isnull()
# df.isnull().sum()
# df.isnull().sum() / len(df)

df.isnull().sum() / len(df)

first_name       0.2
last_name        0.2
age              0.2
sex              0.2
preTestScore     0.4
postTestScore    0.4
dtype: float64

In [ ]:
# 결측치가 있는 행을 삭제

df.dropna()

# 결과 : ??

  first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

In [4]:
# 위에서 삭제된 내용이 저장되지 않았다!
df

  first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0           25.0
1        NaN       NaN   NaN  NaN           NaN            NaN
2       Tina       Ali  36.0    f           NaN            NaN
3       Jake    Milner  24.0    m           2.0           62.0
4        Amy     Cooze  73.0    f           3.0           70.0

In [5]:
# 삭제된 결과를 다른 객체에 저장

df_no_missing = df.dropna()
df_no_missing

  first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

In [ ]:
df.dropna(how='all')

# 결과 : 행의 모든 컬럼이 널이면 삭제

  first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
2       Tina       Ali  36.0   f           NaN            NaN
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

In [ ]:
df.dropna(how='any')

# 결과 : 행의 하나라도 널이면 삭제

  first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

In [8]:
# thresh=1 :  결측치가 아닌 값이 최소 1개 이상 있는 행만 유지

df.dropna(thresh=1)

  first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
2       Tina       Ali  36.0   f           NaN            NaN
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

In [9]:
# 결측치가 아닌 값이 5개 이상 있는 행만 유지

df.dropna(thresh=5)

  first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

### 결측치 처리 : 변환
- 데이터가 없는 값을 특정값으로 변환
- 평균값, 최빈값, 중간값으로 변환

In [11]:
df

  first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0           25.0
1        NaN       NaN   NaN  NaN           NaN            NaN
2       Tina       Ali  36.0    f           NaN            NaN
3       Jake    Milner  24.0    m           2.0           62.0
4        Amy     Cooze  73.0    f           3.0           70.0

In [12]:
# 결측치를 0으로 변환

df.fillna(0)

  first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
1          0         0   0.0   0           0.0            0.0
2       Tina       Ali  36.0   f           0.0            0.0
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

In [ ]:
# preTestScore 열의 값 중 결측치 값을 중앙값으로 변환

df["preTestScore"].fillna(df["preTestScore"].median())

0    4.0
1    3.0
2    3.0
3    2.0
4    3.0
Name: preTestScore, dtype: float64

### 범주형 데이터 처리 : 원핫인코딩(one-hot encoding)
- 범주형데이터의 갯수만큼 가변수를 생성 존재유무를 1 또는 0 으로 표현

In [15]:
df = pd.DataFrame({'source': [0, 1, 2],
                   'target': [2, 2, 3],
                   'weight': [3, 4, 5],
                   'color' : ['red', 'blue', 'blue']})
df

   source  target  weight color
0       0       2       3   red
1       1       2       4  blue
2       2       3       5  blue

In [16]:
df.dtypes

source    int64
target    int64
weight    int64
color       str
dtype: object

In [18]:
# 판다스 : get_dummies 사용
# 사이킷런 : OneHotEncoder, LabelEncoder 사용

#pd.get_dummies(df)

pd.get_dummies(df).astype(int)

   source  target  weight  color_blue  color_red
0       0       2       3           0          1
1       1       2       4           1          0
2       2       3       5           1          0

### 범주형 데이터 처리
- 기수형 데이터 -> 명목형으로 변경 -> 원핫인코딩 적용

In [19]:
df1 = pd.DataFrame({'source': [0, 1, 2],
                    'target': [2, 2, 3],
                    'weight': [3, 4, 5],
                    'color' : ['red', 'blue', 'blue']})
df1

   source  target  weight color
0       0       2       3   red
1       1       2       4  blue
2       2       3       5  blue

In [20]:
# weight 데이터는 숫자로 되어 있지만 연속형 데이터가 아니고 기수형 데이터다
# weight 데이터 -> 명목형으로 변경 -> 원핫인코딩 적용

weight_dict = {3:"M", 4:"L", 5:"XL"}
df1["weight_sign"] = df1["weight"].map(weight_dict)
df1

   source  target  weight color weight_sign
0       0       2       3   red           M
1       1       2       4  blue           L
2       2       3       5  blue          XL

In [21]:
# 혹시 True false 나오면 뒤에 astype(int) 해준다

#weight_sign = pd.get_dummies(df1["weight_sign"])
weight_sign = pd.get_dummies(df1["weight_sign"]).astype(int)
weight_sign

   L  M  XL
0  0  1   0
1  1  0   0
2  0  0   1

In [22]:
# 두 데이터프레임 결합
# axis=1 좌우로 결합

pd.concat([df1, weight_sign], axis=1)

   source  target  weight color weight_sign  L  M  XL
0       0       2       3   red           M  0  1   0
1       1       2       4  blue           L  1  0   0
2       2       3       5  blue          XL  0  0   1

### 범주형 데이터 처리 : 바인딩
- 연속형 데이터 -> 범주형 데이터로 처리

In [23]:
# 3개 부대 소속 군인들의 시험 전후 점수

raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'],
            'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

# df = pd.DataFrame(raw_data)
df = pd.DataFrame(raw_data, columns = ['regiment', 'company', 'name', 'preTestScore', 'postTestScore'])
df

      regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70

In [24]:
# 연속형 데이터 -> 범주형 데이터로 변환
# cut 함수 사용
# 교재 227  : 범위 잘못 됨!!

bins = [0, 25, 50, 75, 100]  # bins 정의(0-25, 26-50, 51-75, 75-100)
group_names = ['Low', 'Okay', 'Good', 'Great']

df['categories'] = pd.cut(df['postTestScore'], bins, labels=group_names)

df

      regiment company      name  preTestScore  postTestScore categories
0   Nighthawks     1st    Miller             4             25        Low
1   Nighthawks     1st  Jacobson            24             94      Great
2   Nighthawks     2nd       Ali            31             57       Good
3   Nighthawks     2nd    Milner             2             62       Good
4     Dragoons     1st     Cooze             3             70       Good
5     Dragoons     1st     Jacon             4             25        Low
6     Dragoons     2nd    Ryaner            24             94      Great
7     Dragoons     2nd      Sone            31             57       Good
8       Scouts     1st     Sloan             2             62       Good
9       Scouts     1st     Piger             3             70       Good
10      Scouts     2nd     Riani             2             62       Good
11      Scouts     2nd       Ali             3             70       Good

### 데이터 크기 맞추기 : 피쳐 스케일링
- 최대값-최대값 정규화 : 0~1 사이의 값으로 매핑하는 기법
- z-스코어 정규형 : 기존값을 표준 정규분포 값으로 변환하는 기법

In [25]:
df = pd.DataFrame(
    {'A':[14.00,90.20,90.95,96.27,91.21],
     'B':[103.02,107.26,110.35,114.23,114.68],
     'C':['big','small','big','small','small']})

df

       A       B      C
0  14.00  103.02    big
1  90.20  107.26  small
2  90.95  110.35    big
3  96.27  114.23  small
4  91.21  114.68  small

In [26]:
# A열에 전체적으로 최소값을 빼준다

df["A"] - df["A"].min()

0     0.00
1    76.20
2    76.95
3    82.27
4    77.21
Name: A, dtype: float64

In [ ]:
# 공식에 그대로 대입
# 최소값-최대값 정규화

( df["A"] - df["A"].min() ) / (df["A"].max() - df["A"].min())

0    0.000000
1    0.926219
2    0.935335
3    1.000000
4    0.938495
Name: A, dtype: float64

In [29]:
( df["B"] - df["B"].min() ) / (df["B"].max() - df["B"].min())

0    0.000000
1    0.363636
2    0.628645
3    0.961407
4    1.000000
Name: B, dtype: float64

In [28]:
# z-스코어 정규형 : 기존값을 표준 정규분포 값으로 변환하는 기법

( df["B"] - df["B"].mean() ) / (df["B"].std() )

0   -1.405250
1   -0.540230
2    0.090174
3    0.881749
4    0.973556
Name: B, dtype: float64