## ch04 - section 3
- 그룹별 집계
- 그룹화된 상태 : 집계, 변환, 필터

In [34]:
import pandas as pd
import numpy as np

data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings','Kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
        'Rank': [1, 2, 2, 3, 3, 4, 1, 1, 2, 4, 1, 2],
        'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
        'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}

df = pd.DataFrame(data)
df

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    Kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Team    12 non-null     str
 1   Rank    12 non-null     int64
 2   Year    12 non-null     int64
 3   Points  12 non-null     int64
dtypes: int64(3), str(1)
memory usage: 516.0 bytes

In [36]:
# df.groupby(묶음의 기준이 되는 열)[연산을 적용할 열].적용할연산함수
# 팀별 포인트의 합계

df.groupby('Team')['Points'].sum()

Team
Devils    1536
Kings     3097
Riders    3049
Royals    1505
Name: Points, dtype: int64

In [37]:
# 팀별 포인트의 평균

df.groupby("Team")["Points"].mean()

Team
Devils    768.00
Kings     774.25
Riders    762.25
Royals    752.50
Name: Points, dtype: float64

In [38]:
# 멀티인덱스
# 한 개 이상의 열을 기준으로 그룹별 집계를 실행
# 팀별 년도별 포인트의 합계

df.groupby(['Team', 'Year'])['Points'].sum()

Team    Year
Devils  2014    863
        2015    673
Kings   2014    741
        2015    812
        2016    756
        2017    788
Riders  2014    876
        2015    789
        2016    694
        2017    690
Royals  2014    701
        2015    804
Name: Points, dtype: int64

## 그룹화된 상태에서 집계, 변환, 필터
- 그룹화된 상태란  분할 > 적용 > 결합 이어지는 groupby 함수 사용에서 분할만 적용한 상태

In [39]:
# 위의 df 데이터프레임 사용

grouped = df.groupby('Team')
# grouped  -> 아무것도 출력되지 않는다

grouped

In [19]:
grouped.get_group(['Kings', 'Royals'])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [40]:
grouped.get_group('Kings')

    Team  Rank  Year  Points
4  Kings     3  2014     741
5  Kings     4  2015     812
6  Kings     1  2016     756
7  Kings     1  2017     788

In [41]:
# 그룹화된 상태에서 집계 : agg 함수
# 팀별로 그룹화한 후 'Points'의 합계

# df.groupby("Team").agg({'Points':'sum'})

df.groupby("Team").agg({'Points':['sum', 'mean']})

       Points
          sum    mean
Team
Devils   1536  768.00
Kings    3097  774.25
Riders   3049  762.25
Royals   1505  752.50

In [16]:
# agg 함수는 groupby나 DataFrame/Series에 적용해서 다양한 연산을 한 번에 할 수 있다.
# 팀별 포인트 컬럼에 합계, 평균, 최대값

df.groupby("Team").agg({ "Points": ['sum', 'mean', 'max'] } )

       Points
          sum    mean  max
Team
Devils   1536  768.00  863
Kings    3097  774.25  812
Riders   3049  762.25  876
Royals   1505  752.50  804

### 유용한 데이터프레임 조작 기능
- 열추가
- 정렬 : 오름차순, 내림차순

In [43]:
import pandas as pd

x=[0, 1, 2, 3, 3, 4]
y=[0, 2, 4, 6, 8, 10]

df=pd.DataFrame( )

df['x']=x      # 컬럼(열) 추가 / 없는 열이면 추가
df['y']=y      # 컬럼(열) 추가


df

   x   y
0  0   0
1  1   2
2  2   4
3  3   6
4  3   8
5  4  10

In [44]:
# 연산 결과를 열로 추가
# x 컬럼의 값 * y 컬럼의 값을 xy 컬럼으로 추가

df['xy'] = df['x'] * df['y']
df

   x   y  xy
0  0   0   0
1  1   2   2
2  2   4   8
3  3   6  18
4  3   8  24
5  4  10  40

In [45]:
# 특정 열을 기준으로 정렬하기: sort_values 함수
# 기본은 오름차순

# by 생략 가능

# df.sort_values(by='x')

df.sort_values(by='x', ascending=True)

   x   y  xy
0  0   0   0
1  1   2   2
2  2   4   8
3  3   6  18
4  3   8  24
5  4  10  40

In [46]:
# 내림차순
df.sort_values(by='x', ascending=False)

   x   y  xy
5  4  10  40
3  3   6  18
4  3   8  24
2  2   4   8
1  1   2   2
0  0   0   0

In [22]:
# by 생략가능, ascending = True  기본이므로 생략가능
df.sort_values('x')

   x   y  xy
0  0   0   0
1  1   2   2
2  2   4   8
3  3   6  18
4  3   8  24
5  4  10  40

In [23]:
# 여러 컬럼으로 정렬

df.sort_values(by=['x','y'], ascending=[False,True])

   x   y  xy
5  4  10  40
3  3   6  18
4  3   8  24
2  2   4   8
1  1   2   2
0  0   0   0

## 셀프스터디
- 데이터셋 :  온라인 쇼핑몰 주문 기록
  ->  customer, product, category, price, quantity 콴티티 수량

In [24]:
import pandas as pd

data = {
    'Customer': ['Jane', 'Tom', 'Jane', 'Sara', 'Tom', 'Jane'],
    'Product': ['Blender', 'Tennis Racket', 'Laptop', 'Blender', 'Laptop', 'Yoga Mat'],
    'Category': ['Home & Kitchen', 'Sports & Outdoors', 'Electronics', 'Home & Kitchen', 'Electronics', 'Sports & Outdoors'],
    'Price': [80, 120, 950, 80, 920, 35],
    'Quantity': [1, 5, 4, 2, 2, 1]
}

orders = pd.DataFrame(data)
orders

  Customer        Product           Category  Price  Quantity
0     Jane        Blender     Home & Kitchen     80         1
1      Tom  Tennis Racket  Sports & Outdoors    120         5
2     Jane         Laptop        Electronics    950         4
3     Sara        Blender     Home & Kitchen     80         2
4      Tom         Laptop        Electronics    920         2
5     Jane       Yoga Mat  Sports & Outdoors     35         1

In [25]:
# 문제 1
# 각 고객별 총 주문 금액(Price × Quantity 합계)을 구하시오.
# orders['Total'] 컬럼을 추가하고 -> 고객별 총주문금액 구하기

orders['Total'] = orders['Price'] * orders['Quantity']
result1 = orders.groupby('Customer')['Total'].sum()
result1

Customer
Jane    3915
Sara     160
Tom     2440
Name: Total, dtype: int64

In [27]:
# 문제 2
# 각 상품(Product)별 총 판매 수량 구하시오.
# 단, 가장 많이 팔린 상품부터 출력 (내림차순 정렬)

result2 = orders.groupby('Product')['Quantity'].sum().sort_values(ascending=False)
result2

Product
Laptop           6
Tennis Racket    5
Blender          3
Yoga Mat         1
Name: Quantity, dtype: int64

In [28]:
# 문제 3
# 고객별로 총 구매 수량과 평균 상품 가격을 구하시오.

result3 = orders.groupby('Customer').agg({'Quantity':'sum', 'Price':'mean'})
result3

          Quantity  Price
Customer
Jane             6  355.0
Sara             2   80.0
Tom              7  520.0